all: helloapp.exe

helloapp.exe: helloapp.cpp helloapp.def
	cl /AM /O1 /F 1000 helloapp.def helloapp.cpp /link /ALIGN:4 /NOD /ONERROR:NOEXE mafxcw mlibcew libw shell commdlg

clean:
	-del *.exe
	-del *.map
	-del *.obj
