CPPFLAGS = /GX /Gy /MT /D_MBCS /D_X86_
LFLAGS = /incremental:no /debug:none /subsystem:windows

all: helloapp.exe

helloapp.exe: helloapp.cpp
	cl $(CPPFLAGS) $** /link $(LFLAGS)

clean:
	-del *.exe
	-del *.map
	-del *.obj
	-del *.bsc
