CPPFLAGS = /GX /Gy /MT /D_MBCS /D_X86_
LFLAGS = /incremental:no /debug:none /subsystem:windows

all: hello.exe

hello.exe: hello.obj hello.res
	link $(LFLAGS) $**

clean:
	-del *.exe
	-del *.map
	-del *.obj
	-del *.bsc
	-del *.res
